Details page added, test written, formatting done
CLebby-code/Django-CRM pull request #17
Opened 2023-07-18 10:57 UTC by CLebby-code

2023-07-18 14:15 UTC, jrlord requested changes
Can you please also link the company name displayed in the customer list

2023-07-18 14:19 UTC, jrlord commented on website/views.py
company_details = Company.objects.get(id=pk)
company_instance = Company.objects.get(id=pk)

You're hitting the db twice for exactly the same thing. You only need one.

2023-07-18 14:25 UTC, jrlord commented on website/views.py
The customers are fetched in the view, and put as the value for the key 'company_customers' in the template context. Fair enough. But then in the template, it is ignored, and {% for customer in company_instance.customers.all %} is done instead. Either leave the template as it is and sort out the template vars (don't put things you don't need in there), or use the template var in the template.

2023-07-19 09:13 UTC, CLebby-code commented
This is done @jrlord

2023-07-19 09:19 UTC, jrlord approved these changes
lgtm

2023-07-19 09:19 UTC, merged